@echo off
setlocal enabledelayedexpansion
title Desktop Dumper v1.0

:: ============================================
:: Desktop Dumper v1.0
:: Developer: mkgirl
:: Backs up Windows Desktop to a ZIP archive
:: with versioning and system information.
:: ============================================

echo ============================================
echo  Desktop Dumper v1.0
echo  Developer: mkgirl
echo ============================================
echo.

:: --- Get locale-independent timestamp ---
for /f "tokens=2 delims==" %%a in ('wmic os get LocalDateTime /value') do set "DT=%%a"
set "YEAR=%DT:~0,4%"
set "MONTH=%DT:~4,2%"
set "DAY=%DT:~6,2%"
set "HOUR=%DT:~8,2%"
set "MINUTE=%DT:~10,2%"
set "SECOND=%DT:~12,2%"
set "TIMESTAMP=%YEAR%-%MONTH%-%DAY%_%HOUR%%MINUTE%%SECOND%"

:: --- Paths ---
set "SCRIPT_DIR=%~dp0"
set "BACKUP_DIR=%SCRIPT_DIR%backups"
set "BACKUP_NAME=desktop-backup_%TIMESTAMP%"
set "BACKUP_PATH=%BACKUP_DIR%\%BACKUP_NAME%"

:: Detect actual Desktop path (handles OneDrive redirection)
for /f "tokens=*" %%a in ('powershell -NoProfile -Command "[Environment]::GetFolderPath('Desktop')"') do set "DESKTOP_DIR=%%a"

:: --- Get script folder name for exclusion ---
for %%i in ("%SCRIPT_DIR%.") do set "SCRIPT_FOLDER=%%~nxi"

:: --- Create directories ---
if not exist "%BACKUP_DIR%" mkdir "%BACKUP_DIR%"
if exist "%BACKUP_PATH%" rmdir /s /q "%BACKUP_PATH%"
mkdir "%BACKUP_PATH%"

echo [1/4] Copying desktop files...
robocopy "%DESKTOP_DIR%" "%BACKUP_PATH%" /E /XD "%SCRIPT_FOLDER%" /NJH /NJS /NP /NDL >nul 2>&1

echo [2/4] Gathering system information...

:: Get OS info via WMIC
for /f "tokens=2 delims==" %%a in ('wmic os get Version /value ^| find "="') do set "OS_VERSION=%%a"
for /f "tokens=2 delims==" %%a in ('wmic os get BuildNumber /value ^| find "="') do set "OS_BUILD=%%a"
for /f "tokens=2 delims==" %%a in ('wmic os get Caption /value ^| find "="') do set "OS_NAME=%%a"

:: Get total desktop size via PowerShell
for /f %%a in ('powershell -NoProfile -Command "(Get-ChildItem -Path \"%DESKTOP_DIR%\" -Recurse -Force -ErrorAction SilentlyContinue ^| Measure-Object -Property Length -Sum).Sum"') do set "TOTAL_SIZE=%%a"
if not defined TOTAL_SIZE set "TOTAL_SIZE=0"

:: Format size with thousand separators
for /f %%a in ('powershell -NoProfile -Command "if (%TOTAL_SIZE% -gt 0) { '{0:N0}' -f %TOTAL_SIZE% } else { '0' }"') do set "TOTAL_SIZE_FMT=%%a"

echo [3/4] Creating info file...
set "INFO_FILE=%BACKUP_PATH%\backup-info.txt"

(
echo ========================================
echo  Desktop Backup Information
echo  Generated by Desktop Dumper v1.0
echo  Developer: mkgirl
echo ========================================
echo.
echo Time: %HOUR%:%MINUTE%:%SECOND%
echo Date: %YEAR%-%MONTH%-%DAY%
echo.
echo Desktop Path: %DESKTOP_DIR%
echo Total Desktop Size: %TOTAL_SIZE_FMT% bytes
echo.
echo Operating System: %OS_NAME%
echo OS Version: %OS_VERSION%
echo OS Build: %OS_BUILD%
echo.
echo Username: %USERNAME%
echo Computer Name: %COMPUTERNAME%
echo.
echo Backup Timestamp: %TIMESTAMP%
echo ========================================
) > "%INFO_FILE%"

echo [4/4] Creating ZIP archive...
powershell -NoProfile -Command "Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('%BACKUP_PATH%', '%BACKUP_PATH%.zip')"

:: Cleanup
if exist "%BACKUP_PATH%.zip" (
    rmdir /s /q "%BACKUP_PATH%"
    echo.
    echo Backup completed successfully!
    echo Archive: %BACKUP_PATH%.zip
) else (
    echo.
    echo ERROR: Backup failed!
)

echo.
pause
